export const ADD_TODO_SUCCESSFUL = "ADD_TODO_SUCCESSFUL";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";
export const GET_TODOS_SUCCESSFUL = "GET_TODOS_SUCCESSFUL";
export const GET_TODOS_FAILED = "GET_TODOS_FAILED";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO_SUCCESSFUL = "UPDATE_TODO_SUCCESSFUL";
export const UPDATE_TODO_FAILED = "UPDATE_TODO_FAILED";
export const RESET_TODO_ERROR = "RESET_TODO_ERROR";
